# Generated by Django 2.0.3 on 2018-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
